name: Test On Concrete 5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker image build -t docker5-no-install:8.5.2 tests/assets

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Install Chromedriver
      run: |
       sudo apt-get -y install google-chrome-stable
       LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
       wget -c -nc --retry-connrefused --tries=0 "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
       unzip -o -q chromedriver_linux64.zip
       
    - name: Run Chromedriver
      run: ./chromedriver --port=4444 --url-base=wd/hub --whitelisted-ips=  > /dev/null 2>&1&

    - name: Setup Concrete5
      run: docker run -d --name c5_docker -p 8080:80 -v ${GITHUB_WORKSPACE}/tests/assets/packages:/app/packages docker5-no-install:8.5.2

    - name: Build Test Helpers
      run: ${GITHUB_WORKSPACE}/vendor/bin/codecept build
    
    - name: Run Install Test
      run: ${GITHUB_WORKSPACE}/vendor/bin/codecept run Install
    
    - name: Run Dashboard Test
      run: ${GITHUB_WORKSPACE}/vendor/bin/codecept run Dashboard
    
    - name: Run Page Test
      run: ${GITHUB_WORKSPACE}/vendor/bin/codecept run Page

    - name: Upload html on fail
      if: failure()
      uses: actions/upload-artifact@v1
        with:
          name: html-failure
          path: tests/_output/
